time_blocks:
    # EARLY MORNING
    - 7:00am - 7:25am
    - 7:30am - 7:55am
    - 8:00am - 8:25am
    - 8:30am - 8:55am # 10 min break after
    # MORNING
    - 9:00am - 9:25am
    - 9:30am - 9:55am
    - 10:00am - 10:25am # 10 min break after
    - 10:35am - 11:00am
    - 11:05am - 11:30am
    - 11:35am - 12:00pm # lunch after (30 mins)
    - 12:00pm - 12:25pm
    - 12:30pm - 12:55pm
    - 1:00pm - 1:25pm
    - 1:30pm - 1:55pm # 10 min break after
    - 2:05pm - 2:30pm
    - 2:35pm - 3:00pm
    - 3:05pm - 3:30pm # 10 min break after
    - 3:40pm - 4:05pm
    - 4:10pm - 4:35pm
    - 4:40pm - 5:05pm # dinner after (30 mins)
    - 5:10pm - 5:35pm
    # EVENING
    - 5:35pm - 6:00pm
    - 6:05pm - 6:30pm
    - 6:35pm - 7:00pm # 10 min break after
    - 7:10pm - 7:35pm
    - 7:40pm - 8:05pm
    - 8:10pm - 8:35pm # 10 min break after
    - 8:45pm - 9:10pm
    - 9:15pm - 9:40pm
    - 9:45pm - 10:10pm # 10 min break after
    - 10:20pm - 10:45pm
    - 10:50pm - 11:15pm
    - 11:20pm - 11:45pm # late night snack after (25 mins)
    # SLEEP HOURS 
    - 12:10am - 12:35am # 10 min break after
    - 12:45am - 1:10am
    - 1:15am - 1:40am
    - 1:45am - 2:10am # 10 min break after
    - 2:20am - 2:45am
    - 2:50am - 3:15am
    - 3:20am - 3:45am # 10 min break after
    - 3:55am - 4:20am
    - 4:25am - 4:50am
    - 4:55am - 5:20am # breakfast after (30 mins)
    - 5:25am - 5:50am
    - 5:55am - 6:20am # 10 min break after
    - 6:30am - 6:55am